### ISSUE TITLE
Add multiple responses for mocked endpoints

### ISSUE THREAD

**Issue by vinniimiranda** [WrenchApps/GoWrench#13]
Considering that some endpoints may yield multiple responses (2xx, 4xx, or even 5xx), it would be beneficial to have a list of mock responses. Additionally, if possible, a percentage could be used to determine which response will be returned.

### Sugestion:

```yaml
mock:
- id: success_response
   body: "{ 'Say':'Hello', 'observation': 'Will work' }"
   contentType: "application/json"
   statusCode: 201
   weight: 95
   headers: 
      "mock1": "value1"
      "mock2": "value2"
      "mock3": "value2"

- id: error_response
   body: "{ 'Error':'INVALID_PAYMENT', 'message': 'Fail to create payment due business logic' }"
   contentType: "application/json"
   statusCode: 409
   weight: 5
   headers: 
      "mock1": "value1"
      "mock2": "value2"
      "mock3": "value2"

```
